name: beyond-grades
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=2.0,<3
  - pandas>=2.2,<3
  - scipy>=1.16,<2
  - scikit-learn>=1.4,<2
  - joblib>=1.5,<2
  - threadpoolctl>=3.6,<4
  - matplotlib>=3.9,<4
  - seaborn>=0.13,<1
  - jupyterlab>=4.1,<5
  - ipykernel>=6.29,<7
  - xgboost>=2.1,<3