name: beyond-grades
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.10
  - numpy=1.26.*           # compatible with sklearn 1.4/1.5 and SciPy
  - pandas=2.2.*           
  - scipy=1.11.*           # stats tests used (shapiro, ttest_rel, wilcoxon, pearsonr)
  - scikit-learn=1.4.*     # pipelines, CV, permutation_importance, etc.
  - xgboost=2.1.*          # you import xgboost
  - joblib=1.3.*           # used directly; sklearn depends on it too
  - threadpoolctl=3.5.*    # sklearn runtime control

  # Plotting / EDA
  - matplotlib=3.8.*       # safe with NumPy 1.26
  - seaborn=0.13.*         # you call sns.set_theme

  # Notebooks
  - jupyterlab=4.1.*
  - ipykernel=6.29.*

  # Utilities
  - pip
  - pip:
      - watermark==2.4.3   # optional: show env/package versions inside notebooks
