# config.yml

project:
  name: "student-performance-regression"
  author: "Enrico Vaccari"
  version: "1.0"
  seed: 42

paths:
  raw_data: "data/raw/student_data.csv"
  processed_data: "data/processed/cleaned_data.csv"
  feature_summary: "data/docs/feature_summary.csv"
  output_dir: "outputs/"
  models_dir: "models/"

notebooks:
  run_order:
    - "notebooks/01_EDA.ipynb"
    - "notebooks/02_Regression.ipynb"
    - "notebooks/03_Model_Comparison.ipynb"

target:
  name: "GPA"

features:
  numeric:
    - Age
    - StudyTimeWeekly
    - Absences
  categorical:
    - Gender
    - Ethnicity
    - ParentalEducation
    - ParentalSupport
    - Tutoring
    - Sports
    - Music
    - Extracurricular
    - Volunteering

modeling:
  test_size: 0.2
  cv_folds: 5
  scoring: "r2"
  scale_numeric: true
  encode_categorical: true

logging:
  level: "INFO"
  log_file: "logs/pipeline.log"
